version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     networks:
       - backend
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: jtoset/fem-un-docker
     volumes:
       - wp_data:/var/www/html
     ports:
       - "8000:80"
     restart: always
     networks:
       - backend
       - frontend
volumes:
    db_data: {}
    wp_data: {}

networks:
    frontend: {}
    backend: {}  
